# --- KONFIGURACJA SPRZĘTOWA ---
bus:
  interface: "kvaser"
  channel: 0
  bitrate: 1000000

# --- WYBÓR AKTYWNEGO TESTU ---
# Zmień tę nazwę, aby przełączyć się na inną płytkę z listy poniżej
active_target: "Frontbox"

# --- PROFILE URZĄDZEŃ (Dynamiczna część) ---
targets:
  Frontbox:
    rx_frame: "Rearbox_Safety"    # Co tester wysyła (Watchdog dla FB)
    tx_frame: "Pc_MainData"       # Co tester odbiera (Dane z FB)
    timeout_ms: 150

  BMS_LV:
    rx_frame: "Dashboard"         # Przykładowa ramka sterująca
    tx_frame: "Bms_LV_main"       # Dane z BMS
    timeout_ms: 100

  Inverter_Rear:
    rx_frame: "AmkRearLeftSetpoints1"
    tx_frame: "AmkRearLeftActualValues1"
    timeout_ms: 20

# --- ŚCIEŻKI ---
paths:
  logs: "logs"
  reports: "reports"